[package]
name = "minimal-tcp-terminal"
version = "0.1.0"
authors = ["Bastian Gruber <foreach@me.com>", "chrisVillanueva"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
